spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/bmutziu/eks-blueprints-workloads
    targetRevision: main
  ingress:
    host: dev.bmutziu.me
